/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#7df4ff",
        "secondary-fixed": "#f4d9ff",
        "surface-container-low": "#151b2d",
        "secondary-container": "#a100f0",
        "error": "#ffb4ab",
        "surface-container-high": "#23293c",
        "on-background": "#dce1fb",
        "primary-fixed-dim": "#00dbe9",
        "surface-bright": "#33394c",
        "error-container": "#93000a",
        "on-tertiary-container": "#006d4a",
        "secondary-fixed-dim": "#e5b5ff",
        "on-tertiary": "#003824",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#070d1f",
        "inverse-primary": "#006970",
        "on-primary-container": "#006970",
        "on-secondary-container": "#f7e1ff",
        "inverse-on-surface": "#2a3043",
        "inverse-surface": "#dce1fb",
        "primary": "#dbfcff",
        "surface-dim": "#0c1324",
        "surface-tint": "#00dbe9",
        "surface": "#0c1324",
        "on-error": "#690005",
        "surface-container": "#191f31",
        "tertiary": "#d8ffe7",
        "on-surface-variant": "#b9cacb",
        "on-tertiary-fixed-variant": "#005236",
        "outline": "#849495",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#7000a8",
        "surface-container-highest": "#2e3447",
        "background": "#0c1324",
        "on-secondary-fixed": "#30004b",
        "outline-variant": "#3b494b",
        "on-secondary": "#4e0078",
        "on-primary-fixed": "#002022",
        "surface-variant": "#2e3447",
        "primary-container": "#00f0ff",
        "on-primary": "#00363a",
        "tertiary-container": "#65f2b5",
        "on-surface": "#dce1fb",
        "on-primary-fixed-variant": "#004f54",
        "secondary": "#e5b5ff",
        cyber: {
          950: '#020617',
          900: '#050c1e',
          850: '#081329',
          800: '#0d1d3a',
          700: '#142a54',
          600: '#1e3e7b',
        },
        neon: {
          cyan: '#00f0ff',
          teal: '#00ffc4',
          emerald: '#10b981',
          lime: '#39ff14',
          purple: '#b026ff',
          pink: '#ff007f',
          magenta: '#ff00a0',
          blue: '#3b82f6',
          amber: '#ffb800',
          rose: '#ff3366',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Syne', 'Space Grotesk', 'Outfit', 'sans-serif'],
        'display-xl': ['Syne', 'sans-serif'],
        'display-lg': ['Syne', 'Space Grotesk', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Space Grotesk', 'Inter', 'sans-serif'],
        'body-md': ['Space Grotesk', 'Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        orbitron: ['Orbitron', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        unit: "4px",
        "panel-padding": "20px",
        margin: "32px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        gutter: "24px"
      },
      boxShadow: {
        'neon-cyan': '0 0 25px -5px rgba(0, 240, 255, 0.45)',
        'neon-emerald': '0 0 25px -5px rgba(16, 185, 129, 0.45)',
        'neon-purple': '0 0 25px -5px rgba(176, 38, 255, 0.45)',
        'neon-pink': '0 0 25px -5px rgba(255, 0, 127, 0.45)',
        'neon-amber': '0 0 25px -5px rgba(255, 184, 0, 0.45)',
        'cyber-glass': '0 20px 50px rgba(0, 0, 0, 0.75), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
        'glow-box': '0 0 40px -10px rgba(0, 240, 255, 0.25), inset 0 0 20px rgba(0, 240, 255, 0.05)',
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        'float-slow': 'floatSlow 6s ease-in-out infinite',
        'float-reverse': 'floatReverse 7s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'laser-scan': 'laserScan 2.5s ease-in-out infinite',
        'border-flow': 'borderFlow 4s linear infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'glitch': 'glitch 1s linear infinite',
        'scan': 'scan 3s linear infinite',
      }
    },
  },
  plugins: [],
}
